package observer

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"terraform-provider-manifestit/pkg/sdk"
	sdkErrors "terraform-provider-manifestit/pkg/sdk/errors"
)

const (
	PostOpenMaxRetries = 3
	PostOpenRetryBase  = 500 * time.Millisecond
	PostOpenRetryMax   = 5 * time.Second
	CloseDeadline      = 25 * time.Second
)

// Client defines the observer API operations.
type Client interface {
	// Post publishes an "open" event at apply start. Retries with exponential backoff.
	Post(ctx context.Context, input ObserverPayload) (*ObserverResponse, error)
	// Patch publishes a "closed" event. Returns nil on 409/410 (idempotent).
	Patch(ctx context.Context, runID string, input ClosePayload) (*ObserverResponse, error)
}

// ObserverPayload is the payload posted to open a run observation.
type ObserverPayload struct {
	// RunID is a UUID generated by the provider at the start of the run.
	// The same UUID is used in the subsequent Patch (close) call.
	RunID         string `json:"run_id"`
	Status        string `json:"status"` // "open"
	Identity      any    `json:"identity,omitempty"`
	Git           any    `json:"git,omitempty"`
	CollectedAt   string `json:"collected_at"`
	Action        string `json:"action"` // "apply", "plan", "destroy"
	OrgID         string `json:"org_id,omitempty"`
	ProviderCfgID string `json:"provider_cfg_id,omitempty"`
}

// ClosePayload is the payload PATCHed to close a run observation.
type ClosePayload struct {
	RunID         string `json:"run_id"`
	Status        string `json:"status"` // "closed" or "heartbeat"
	Identity      any    `json:"identity,omitempty"`
	Git           any    `json:"git,omitempty"`
	CollectedAt   string `json:"collected_at"`
	Action        string `json:"action"`
	OrgID         string `json:"org_id,omitempty"`
	ProviderCfgID string `json:"provider_cfg_id,omitempty"`
}

// ObserverResponse is the API response from posting an observation.
type ObserverResponse struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

const basePath = "/events"

// client implements Client using the SDK's APIClient.
type client struct {
	api *sdk.APIClient
}

// New creates an observer Client backed by the given APIClient.
func New(api *sdk.APIClient) Client {
	return &client{api: api}
}

func (c *client) Post(ctx context.Context, input ObserverPayload) (*ObserverResponse, error) {
	var lastErr error
	backoff := PostOpenRetryBase

	for attempt := 0; attempt <= PostOpenMaxRetries; attempt++ {
		if attempt > 0 {
			// Exponential backoff with cap, interruptible by context cancellation.
			select {
			case <-ctx.Done():
				return nil, fmt.Errorf("observer post cancelled: %w", ctx.Err())
			case <-time.After(backoff):
			}
			backoff *= 2
			if backoff > PostOpenRetryMax {
				backoff = PostOpenRetryMax
			}
		}

		body, status, err := c.api.Post(ctx, basePath, input)
		if err != nil {
			lastErr = fmt.Errorf("observer post failed: %w", err)
			continue // retry on transport/timeout error
		}
		if hErr := sdkErrors.Handle(status, body); hErr != nil {
			lastErr = hErr
			if !isTransient(status) {
				return nil, lastErr // non-retryable client error (4xx)
			}
			continue
		}

		var result ObserverResponse
		if len(body) > 0 {
			if err := json.Unmarshal(body, &result); err != nil {
				return nil, fmt.Errorf("failed to parse observer response: %w", err)
			}
		}
		return &result, nil
	}

	return nil, fmt.Errorf("observer post failed after %d retries: %w", PostOpenMaxRetries, lastErr)
}

// PatchMaxRetries is the number of retries for PATCH /closed.
const PatchMaxRetries = 3

func (c *client) Patch(ctx context.Context, runID string, input ClosePayload) (*ObserverResponse, error) {
	var lastErr error
	backoff := PostOpenRetryBase // reuse same base (500ms)

	for attempt := 0; attempt <= PatchMaxRetries; attempt++ {
		if attempt > 0 {
			select {
			case <-ctx.Done():
				return nil, fmt.Errorf("observer patch cancelled: %w", ctx.Err())
			case <-time.After(backoff):
			}
			backoff *= 2
			if backoff > PostOpenRetryMax {
				backoff = PostOpenRetryMax
			}
		}

		body, status, err := c.api.Patch(ctx, basePath+"/"+runID, input)

		// 409 Conflict or 410 Gone: event already closed/timed-out — idempotent.
		if status == http.StatusConflict || status == http.StatusGone {
			return &ObserverResponse{}, nil
		}

		if err != nil {
			lastErr = fmt.Errorf("observer patch failed: %w", err)
			continue // retry on transport error
		}

		if hErr := sdkErrors.Handle(status, body); hErr != nil {
			lastErr = hErr
			if !isTransient(status) {
				return nil, lastErr // non-retryable (e.g. 404 bad run_id)
			}
			continue
		}

		var result ObserverResponse
		if len(body) > 0 {
			if err := json.Unmarshal(body, &result); err != nil {
				return nil, fmt.Errorf("failed to parse observer patch response: %w", err)
			}
		}
		return &result, nil
	}

	return nil, fmt.Errorf("observer patch failed after %d retries: %w", PatchMaxRetries, lastErr)
}

// isTransient returns true for HTTP status codes that warrant a retry.
func isTransient(status int) bool {
	return status == http.StatusTooManyRequests ||
		status == http.StatusServiceUnavailable ||
		status == http.StatusGatewayTimeout ||
		status == http.StatusBadGateway ||
		status == http.StatusRequestTimeout ||
		(status >= 500 && status < 600)
}
