package observer

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"terraform-provider-manifestit/pkg/sdk"
	sdkErrors "terraform-provider-manifestit/pkg/sdk/errors"
)

// Timing and retry constants for all observer API calls.
const (
	// HeartbeatDeadline is the per-call HTTP timeout for heartbeat requests.
	HeartbeatDeadline = 10 * time.Second
	// HeartbeatMaxRetries is the number of retries for heartbeat calls.
	// Heartbeats are frequent so only 2 retries are used with a fixed delay.
	HeartbeatMaxRetries = 2
	// HeartbeatRetryDelay is the fixed retry delay for heartbeat calls.
	HeartbeatRetryDelay = 200 * time.Millisecond

	// PostOpenMaxRetries is the number of retries for POST /open.
	PostOpenMaxRetries = 3
	// PostOpenRetryBase is the base for exponential backoff on POST /open.
	PostOpenRetryBase = 500 * time.Millisecond
	// PostOpenRetryMax caps exponential backoff.
	PostOpenRetryMax = 5 * time.Second

	// CloseDeadline is the per-call HTTP timeout for PATCH /closed.
	CloseDeadline = 25 * time.Second
)

// Client defines the interface for observer API operations.
type Client interface {
	// Post publishes an "open" event at the start of a terraform run.
	// Retries up to PostOpenMaxRetries times with exponential backoff.
	Post(ctx context.Context, input ObserverPayload) (*ObserverResponse, error)
	// Patch publishes a "closed" or "heartbeat" event.
	// Returns nil on 409/410 (already closed — idempotent).
	Patch(ctx context.Context, runID string, input ClosePayload) (*ObserverResponse, error)
	// Heartbeat sends a heartbeat PATCH to keep the event alive on the server.
	// Creates its own context with HeartbeatDeadline independent of the caller's context.
	// Non-fatal: returns error on exhaustion but never panics.
	Heartbeat(ctx context.Context, runID string) error
}

// ObserverPayload is the payload posted to open a run observation.
type ObserverPayload struct {
	// RunID is a UUID generated by the provider at the start of the run.
	// The same UUID is used in the subsequent Patch (close) call.
	RunID       string `json:"run_id"`
	Status      string `json:"status"` // "open"
	Identity    any    `json:"identity,omitempty"`
	Git         any    `json:"git,omitempty"`
	CollectedAt string `json:"collected_at"`
	Action      string `json:"action"` // "apply", "plan", "destroy"
	OrgID       string `json:"org_id,omitempty"`
}

// ClosePayload is the payload PATCHed to close a run observation.
type ClosePayload struct {
	Status      string `json:"status"` // "closed" or "heartbeat"
	Identity    any    `json:"identity,omitempty"`
	Git         any    `json:"git,omitempty"`
	CollectedAt string `json:"collected_at"`
	Action      string `json:"action"`
	OrgID       string `json:"org_id,omitempty"`
}

// ObserverResponse is the API response from posting an observation.
type ObserverResponse struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

const basePath = "/api/v1/events"

// client implements Client using the SDK's APIClient.
type client struct {
	api *sdk.APIClient
}

// New creates an observer Client backed by the given APIClient.
func New(api *sdk.APIClient) Client {
	return &client{api: api}
}

func (c *client) Post(ctx context.Context, input ObserverPayload) (*ObserverResponse, error) {
	var lastErr error
	backoff := PostOpenRetryBase

	for attempt := 0; attempt <= PostOpenMaxRetries; attempt++ {
		if attempt > 0 {
			// Exponential backoff with cap, interruptible by context cancellation.
			select {
			case <-ctx.Done():
				return nil, fmt.Errorf("observer post cancelled: %w", ctx.Err())
			case <-time.After(backoff):
			}
			backoff *= 2
			if backoff > PostOpenRetryMax {
				backoff = PostOpenRetryMax
			}
		}

		body, status, err := c.api.Post(ctx, basePath, input)
		if err != nil {
			lastErr = fmt.Errorf("observer post failed: %w", err)
			continue // retry on transport/timeout error
		}
		if hErr := sdkErrors.Handle(status, body); hErr != nil {
			lastErr = hErr
			if !isTransient(status) {
				return nil, lastErr // non-retryable client error (4xx)
			}
			continue
		}

		var result ObserverResponse
		if len(body) > 0 {
			if err := json.Unmarshal(body, &result); err != nil {
				return nil, fmt.Errorf("failed to parse observer response: %w", err)
			}
		}
		return &result, nil
	}

	return nil, fmt.Errorf("observer post failed after %d retries: %w", PostOpenMaxRetries, lastErr)
}

func (c *client) Patch(ctx context.Context, runID string, input ClosePayload) (*ObserverResponse, error) {
	body, status, err := c.api.Patch(ctx, basePath+"/"+runID, input)

	// 409 Conflict or 410 Gone: event already closed/timed-out — idempotent, not an error.
	// Check status first; HTTPExecutor returns a non-nil error for all 4xx but
	// also returns the numeric status so we can distinguish 409/410 here.
	if status == http.StatusConflict || status == http.StatusGone {
		return &ObserverResponse{}, nil
	}

	if err != nil {
		return nil, fmt.Errorf("observer patch failed: %w", err)
	}

	if hErr := sdkErrors.Handle(status, body); hErr != nil {
		return nil, hErr
	}

	var result ObserverResponse
	if len(body) > 0 {
		if err := json.Unmarshal(body, &result); err != nil {
			return nil, fmt.Errorf("failed to parse observer patch response: %w", err)
		}
	}
	return &result, nil
}

// Heartbeat sends a { "status": "heartbeat" } PATCH to keep the server event
// alive. It always creates its own independent context with HeartbeatDeadline
// so a cancelled parent context does not prevent the call from running.
// Retries twice with a fixed HeartbeatRetryDelay before returning an error.
func (c *client) Heartbeat(_ context.Context, runID string) error {
	payload := ClosePayload{Status: "heartbeat"}

	var lastErr error
	for attempt := 0; attempt <= HeartbeatMaxRetries; attempt++ {
		if attempt > 0 {
			time.Sleep(HeartbeatRetryDelay)
		}

		// Use an independent context — caller cancellation must not block heartbeat.
		hbCtx, cancel := context.WithTimeout(context.Background(), HeartbeatDeadline)
		body, status, err := c.api.Patch(hbCtx, basePath+"/"+runID, payload)
		cancel()

		// 409/410: event already closed — heartbeat is a no-op, not an error.
		// Check status first (HTTPExecutor returns both status and error for 4xx).
		if status == http.StatusConflict || status == http.StatusGone {
			return nil
		}
		if err != nil {
			lastErr = fmt.Errorf("heartbeat patch failed: %w", err)
			continue
		}
		if hErr := sdkErrors.Handle(status, body); hErr != nil {
			lastErr = hErr
			continue
		}
		return nil
	}

	return fmt.Errorf("heartbeat failed after %d retries: %w", HeartbeatMaxRetries, lastErr)
}

// isTransient returns true for HTTP status codes that warrant a retry.
func isTransient(status int) bool {
	return status == http.StatusTooManyRequests ||
		status == http.StatusServiceUnavailable ||
		status == http.StatusGatewayTimeout ||
		status == http.StatusBadGateway ||
		status == http.StatusRequestTimeout ||
		(status >= 500 && status < 600)
}
